services:
  loadtest:
    build: ./loadtests
    ports:
      - "8089:8089"
    environment:
      - LOCUST_HOST=http://host.docker.internal:5000
    command: ["-f", "/loadtests/locustfile.py"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docs/results:/results
